# Generated by Django 2.1.5 on 2020-11-02 20:42

from django.db import migrations, models
import street_tag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', validators=[street_tag.models.validate_image])),
            ],
        ),
    ]
