# Generated by Django 2.1.5 on 2020-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
